name: modern_utils
description: "Widgets and functions for routine use."
version: 1.0.0
homepage: https://github.com/priyesh-techabbot/modern_utils

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0